version: "3.3"
services:
  frontend:
    build: front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: backend
    restart: always
    ports:
      - "6969:6969"
